import { Product } from "../../types"

export const plunzhernye_nasosy: Product[] = [
  {
    id: 1,
    name: "Насос высокого давления FKA 5020",
    price: 67400,
    image: "/images/cat-plunger-pumps.jpg",
    inStock: true,
    category: "plunzhernye-nasosy",
    country: "Китай",
    power: 5500,
    maxPressure: 20000,
    performance: 20,
  },
  {
    id: 2,
    name: "Насос высокого давления FKA 5620",
    price: 68100,
    image: "/images/cat-plunger-pumps.jpg",
    inStock: true,
    category: "plunzhernye-nasosy",
    country: "Китай",
    power: 7500,
    maxPressure: 20000,
    performance: 21,
  },
  {
    id: 3,
    name: "Насос высокого давления FKA 6615",
    price: 70200,
    image: "/images/cat-plunger-pumps.jpg",
    inStock: true,
    category: "plunzhernye-nasosy",
    country: "Китай",
    power: 11000,
    maxPressure: 25000,
    performance: 25,
  },
  {
    id: 4,
    name: "Насос высокого давления FKA 7415",
    price: 72000,
    image: "/images/cat-plunger-pumps.jpg",
    inStock: true,
    category: "plunzhernye-nasosy",
    country: "Китай",
    power: 15000,
    maxPressure: 25000,
    performance: 30,
  },
  {
    id: 5,
    name: "Насос высокого давления FKH 32",
    price: null,
    image: "/images/cat-plunger-pumps.jpg",
    inStock: false,
    category: "plunzhernye-nasosy",
    country: "Китай",
    power: 5500,
    maxPressure: 19000,
    performance: 32,
  },
  {
    id: 6,
    name: "Насос высокого давления BM 1525 с регулятором давления и манометром",
    price: 25000,
    image: "/images/product-pump.jpg",
    inStock: true,
    badge: "hit",
    category: "plunzhernye-nasosy",
    country: "Китай",
    power: 5500,
    maxPressure: 25000,
    performance: 15,
  },
  {
    id: 7,
    name: "Насос высокого давления Danau DBC 150B5A/1509A/1508A с регулятором давления",
    price: 24000,
    image: "/images/cat-plunger-pumps.jpg",
    inStock: true,
    category: "plunzhernye-nasosy",
    country: "Китай",
    power: 5500,
    maxPressure: 19000,
    performance: 15,
  },
  {
    id: 8,
    name: "Насос высокого давления Danau DBC 1510A с регулятором давления",
    price: 24500,
    image: "/images/cat-plunger-pumps.jpg",
    inStock: true,
    category: "plunzhernye-nasosy",
    country: "Китай",
    power: 5500,
    maxPressure: 19000,
    performance: 15,
  },
  {
    id: 9,
    name: "Насос высокого давления Danau DBD 1810A с регулятором давления",
    price: 26500,
    image: "/images/cat-plunger-pumps.jpg",
    inStock: true,
    badge: "new",
    category: "plunzhernye-nasosy",
    country: "Китай",
    power: 7500,
    maxPressure: 19000,
    performance: 18,
  },
]
